### ISSUE TITLE
AttributeError: module 'darknet' has no attribute 'load_network'

### ISSUE THREAD

**Issue by Hassan-Berry** [hank-ai/darknet#10]
Im trying to load a darknet model in python and im getting the following error:
**AttributeError: module 'darknet' has no attribute 'load_network'**

I have installed darknet using the instructions provided and it works in the cli.

**Comment by stephanecharette** [comment]
Lots of python-related changed were pushed recently.  As far as I know, this is not a problem.  The example python scripts all seem to work for me.  See https://github.com/hank-ai/darknet/tree/master/src-python#darknetyolo-command-guide-for-python

If this is still an issue, please re-open with additional details, or create a new issue.
