### ISSUE TITLE
Why Darknet is not using rotation as augmentation in object detection task.?

### ISSUE THREAD

**Issue by zirid** [hank-ai/darknet#11]
![Capture](https://github.com/hank-ai/darknet/assets/31682698/01f82ef9-5500-4a3c-a70e-1f4b5bbd393c)

Why the function "load_data_detection" is not using rotation at all.  was it done in purpose?

**Comment by stephanecharette** [comment]
See:  https://github.com/AlexeyAB/darknet/issues/4626
