### ISSUE TITLE
Compile darknet directly using Visual Studio

### ISSUE THREAD

**Issue by 1027663760** [hank-ai/darknet#22]
Can't the compilation method of this repository directly use Visual Studio? The version compilation maintained by AlexeyAB is very simple

**Comment by stephanecharette** [comment]
Yes, it can.  See the instructions in the readme.

**Comment by stephanecharette** [comment]
Direct link to location in the README where it shows how to use CMake and Visual Studio to build:  https://github.com/hank-ai/darknet#windows-cmake-method
