### ISSUE TITLE
 reduce the detection frame rate of tiny 

### ISSUE THREAD

**Issue by Nanmei** [hank-ai/darknet#23]
My video frame rate is 90HZ,the detection frame rate of the yolov4 tiny on ububtu18 reaches 200HZ on 4090 graphics card. How can I reduce the detection frame rate of tiny to reduce the power of the graphics card? Because the graphics card has to do other video detection.
thanks

**Comment by 1027663760** [comment]
do {

fps_time = 1000 / 90
time = GetTickCount()

detect() //1 frame

time = GetTickCount() - time
time = fps_time - time
if (time > 0){
sleep (time)
}

}

**Comment by Nanmei** [comment]
> 做 {
> 
> fps_time = 1000 / 90 时间 = GetTickCount()
> 
> 检测() //1帧
> 
> time = GetTickCount() - 时间 time = fps_time - 时间 if (time > 0){ sleep (time) }
> 
> }
> 
> GetTickCount()：自行替换以获得更高的检测精度，例如Windows上使用QueryperForManceCounter()

Thank you very much. I'll test it now

**Comment by 1027663760** [comment]
> > 做 {
> > fps_time = 1000 / 90 时间 = GetTickCount()
> > 检测() //1帧
> > time = GetTickCount() - 时间 time = fps_time - 时间 if (time > 0){ sleep (time) }
> > }
> > GetTickCount()：自行替换以获得更高的检测精度，例如Windows上使用QueryperForManceCounter()
> 
> Thank you very much. I'll test it now

你这搞得我以为是我这边翻译弄错了

**Comment by Nanmei** [comment]
> > > 做 {
> > > fps_time = 1000 / 90 时间 = GetTickCount()
> > > 检测() //1帧
> > > time = GetTickCount() - 时间 time = fps_time - 时间 if (time > 0){ sleep (time) }
> > > }
> > > GetTickCount()：自行替换以获得更高的检测精度，例如Windows上使用QueryperForManceCounter()
> > 
> > 
> > Thank you very much. I'll test it now
> 
> 你这搞得我以为是我这边翻译弄错了

Thank you very much that it can work.
