### ISSUE TITLE
Cannot open include file: 'cuda_runtime.h'

### ISSUE THREAD

**Issue by jklemmack** [hank-ai/darknet#24]
I am unable to build, so I cannot provide a darknet version.  My issue is as of commit 4f93ab7 on Dec 1.

I have created a clean install of Windows 11 Pro 22H2 (VM), and followed the instructions in the README.

First, I got the following error from cmake:

```
C:\src\darknet\build>cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Building for: Visual Studio 17 2022
CMake Error at CMakeLists.txt:28 (PROJECT):
  VERSION ".." format invalid.


-- Configuring incomplete, errors occurred!
```

I had to modify `CM_version.cmake` to explicitly set the `DARKNET_VERSION_SHORT`.  Great - now I can run cmake.

```
SET (DARKNET_VERSION_SHORT 1.0.0)
```

Then, running the next command,  `msbuild` via command line or Visual Studio, I get several dozen errors saying "Cannot open include file: 'cuda_runtime.h'":
```
>C:\src\darknet\src\darknet.h(41,10): error C1083: Cannot open include file: 'cuda_runtime.h': No such file or directory [C:\src\darknet\build\src\darknetobjlib.vcxproj]
         (compiling source file '../../src/Chart.cpp')

     7>C:\src\darknet\src\darknet.h(41,10): error C1083: Cannot open include file: 'cuda_runtime.h': No such file or directory [C:\src\darknet\build\src\darknetobjlib.vcxproj]
         (compiling source file '../../src/activation_layer.cpp')

         activations.cpp
     7>C:\src\darknet\src\darknet.h(41,10): error C1083: Cannot open include file: 'cuda_runtime.h': No such file or directory [C:\src\darknet\build\src\darknetobjlib.vcxproj]
         (compiling source file '../../src/activations.cpp')

         art.cpp
     7>C:\src\darknet\src\darknet.h(41,10): error C1083: Cannot open include file: 'cuda_runtime.h': No such file or directory [C:\src\darknet\build\src\darknetobjlib.vcxproj]
         (compiling source file '../../src/art.cpp')
```

I have verified the files exist at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include`, but I'm not sure what I've missed to have that folder be included during compile.

**Comment by stephanecharette** [comment]
You definitely should not be modifying anything to get it to build.  People are active on the discord server, and everyone (both Linux and Windows) are building recently without any problems.  Please make sure you follow all the steps exactly as described.

**Comment by stephanecharette** [comment]
> Building for: Visual Studio 17 2022

The build steps describe how to use Visual Studio 2022.  How did you end up with VS 2017?

**Comment by jklemmack** [comment]
> > Building for: Visual Studio 17 2022
> 
> The build steps describe how to use Visual Studio 2022. How did you end up with VS 2017?

"17" is the major build number of the product branded Visual Studio 2022.

![image](https://github.com/hank-ai/darknet/assets/1782307/d044c4b6-8dbe-4257-8ab1-3453aae7ec3e)

**Comment by stephanecharette** [comment]
Sorry, I'm a Linux dev.  Not as familiar with the Windows size of things.

**Comment by jklemmack** [comment]
Closing.  I likely had a corrupt `cmake` environment from a previous setup using the [deprecated AlexyAB darkent](https://github.com/AlexeyAB/darknet).

After moving to a clean Windows 11 VM install and following the directions, it worked.  One note though was that the nVidia CUDNN instructions said to create a folder '%programfiles%\nvidia\cudnn\v8.x.y.z`, but renaming the `x.y.z` with the release number (e.g. `v8.9.5.27`).  However, as was pointed out on Discord, the current makefiles require the folder to be explicitly named `v.8.x` without replacement.
