### ISSUE TITLE
Error after compiling on windows 11 using Cuda 12.3

### ISSUE THREAD

**Issue by sivikee** [hank-ai/darknet#32]
Hello,
I'm having issues running the project on Windows 11. I receive same error with different models, input sources etc.

Full command with logs:
c:\Darknet\bin>C:\Darknet\bin\darknet.exe detect cfg/coco.names cfg/yolov7.cfg yolov7.weights test.jpg
Darknet v2.0-75-g31412920
CUDA runtime version 12030 (v12.3), driver version 12030 (v12.3)
cuDNN version 12020 (v8.9.6), use of half-size floats is ENABLED
=> 0: NVIDIA GeForce RTX 3070 Ti [#8.6], 8.0 GiB
OpenCV v4.8.0

* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* Error location: C:\src\darknet\src-cli\darknet.cpp, darknet_signal_handler(), line #431
* Error message:  signal handler invoked for signal #11
* Version v2.0-75-g31412920 built on Dec 29 2023 13:25:41
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
backtrace (15 entries):
1/15: řJ()
2/15: řJ()
3/15: řJ()
4/15: log2f()
5/15: log2f()
6/15: _C_specific_handler()
7/15: _chkstk()
8/15: RtlFindCharInUnicodeString()
9/15: KiUserExceptionDispatcher()
10/15: KiUserExceptionDispatcher()
11/15: KiUserExceptionDispatcher()
12/15: KiUserExceptionDispatcher()
13/15: KiUserExceptionDispatcher()
14/15: BaseThreadInitThunk()
15/15: RtlUserThreadStart()

I would much appreciate some help!
Thanks

**Comment by stephanecharette** [comment]
The command you posted is definitely invalid.

Please use DarkHelp as your CLI,or check the readme page for Darknet to make sure you are using the correct commands.

**Comment by stephanecharette** [comment]
Checked in a fix just now to detect when this situation happens instead of having darknet segfault.  c244a8d8af992514bf8963b3e81f1cf761991119

**Comment by sivikee** [comment]
Thanks! It's indeed working with the test images and the proper commands, but i'm still experiencing issues with using a webcam:
`darknet detector demo cfg/coco.data cfg/yolov4-tiny.cfg yolov4-tiny.weights -c 0
`

[1;33mskipped validating of argument #7 (0)[0m
Darknet [1;37mv2.0-75-g31412920[0m
CUDA runtime version 12030 ([1;37mv12.3[0m), driver version 12030 ([1;37mv12.3[0m)
cuDNN version 12020 ([1;37mv8.9.6[0m), use of half-size floats is [1;37mENABLED[0m
=> 0: [1;32mNVIDIA GeForce RTX 3070 Ti[0m [#8.6], [1;33m8.0 GiB[0m
OpenCV [1;37mv4.8.0[0m
Demo
net.optimized_memory = 0 
mini_batch = 1, batch = 1, time_steps = 1, train = 0 
Create CUDA-stream - 0 
 Create cudnn-handle 0 
nms_kind: greedynms (1), beta = 0.600000 
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 6.910 
avg_outputs = 310203 
Allocating workspace to transfer between CPU and GPU:  13.3 MiB

 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
video file: 0
Video stream has stopped.
Video stream has stopped.

I checked with both webcam and OBS virtual camera, it's detected by windows, just not by the darknet.exe

Thanks!

**Comment by stephanecharette** [comment]
Please use the discord channel for support.

**Comment by stephanecharette** [comment]
Webcam-specific issue reporting again in discord tonight.  Opened up an issue specific to that problem:  issue #38

Closing this one since the original problem was incorrect use of the CLI.
