### ISSUE TITLE
Which weights to use ?

### ISSUE THREAD

**Issue by TidelyPom** [hank-ai/darknet#39]
Hi, I am training Yolov4 for my own objects. At the end of the training (6000 iterations, 2 classes) I get 3 weights files : yolov4-custom_6000.weights, yolov4-custom_final.weights and yolov4-custom_last.weights, could you please tell me which one of these should I use to get the best results ?

**Comment by stephanecharette** [comment]
You trained incorrectly.

See the readme:  https://github.com/hank-ai/darknet#training

Or the FAQ:  https://www.ccoderun.ca/programming/yolo_faq/#training_command
