### ISSUE TITLE
Training Fails When Folder Name Contains Spaces 

### ISSUE THREAD

**Issue by lordofkillz** [hank-ai/darknet#40]
I've encountered a bug while attempting to train a model using the darknet. It seems that the training process is interrupted and fails to continue when a folder name contains a space (e.g., "new folder"). Below are the details for replication and understanding of the issue.

Bug Description:
When initiating training with the darknet , if the dataset is located within a folder whose name contains a space character, the training does not start, and the process exits prematurely with error messages that point to the issue with the folder name.

Steps to Reproduce:

Create a folder with a space in the name, such as "new folder".
Place the dataset inside this folder.
Run the usual command to start training (`darknet detector -map -dont_show train new folder.data animals.cfg`).
Observe that the training process halts unexpectedly.
Expected Behavior:
The training process should either handle folder names with spaces or provide a clear error message indicating the issue.

Actual Behavior:
The training process stops with clear indication as to the reason.

Environment:

Darknet version: (Darknet v2.0-85-g8f8746d7-dirty)
Operating System: (windows 10/11 home and pro)
This issue was encountered on multiple attempts, and renaming the folder to eliminate the space character resolved the problem, confirming the bug's nature.

**Comment by stephanecharette** [comment]
This may be a Windows-specific issue.  Created a project on Linux with a space in the folder name, and training ran to completion.  Tested with Darknet v2.0-85-g8f8746d.

**Comment by stephanecharette** [comment]
Closing with the above commit.  Please re-open if this is not fixed for you.
