### ISSUE TITLE
Can't build on Ubuntu 22.04 with commands in README.md in Docker

### ISSUE THREAD

**Issue by vavanade** [hank-ai/darknet#42]
In `README.md` it states that: "These instructions assume a system running Ubuntu 22.04." which implies that the following commands are sufficient to build this repo.

However Ubuntu 22.04 (at least the Docker image `nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04`) has CMake version 3.22.1 which is in conflict with `CMAKE_MINIMUM_REQUIRED (VERSION 3.24)` in `CMakeLists.txt` and if one lowers the version that means `	SET (DARKNET_CUDA_ARCHITECTURES "native")` in `CM_dependencies.cmake` does not work (one has to comment it out and uncomment `#	SET (DARKNET_CUDA_ARCHITECTURES "75;80;86")`.

It is not a huge deal but seems like an inaccuracy in the `README.md`.

**Comment by stephanecharette** [comment]
Please carefully re-read the build instructions.  It does state what you need to do.

**Comment by stephanecharette** [comment]
I also recommend you watch the video which _clearly_ shows that the build instructions are correct:  https://www.youtube.com/watch?v=WTT1s8JjLFk

**Comment by vavanade** [comment]
You are right that it is shown in the video that one can update CMake from snap but I would like to refrain from using snap packages inside Docker images since they tend to be bigger than packages from the usual repositories and Docker images are usually only built from the LTS versions so I can't use e.g. 23.10 which has newer CMake easily.

My confusion probably stems from
"If you are using an older version of CMake, such as the one with Ubuntu 18.04 or 20.04"
because it does not list Ubuntu 22.04 as one also with an older version of CMake. I made the errorneous implication that it is not necessary to update it on 22.04. It strictly speaking does not imply that but I'd guess that many others can infer the implicit assumption that it does.

For me it would be clear if it stated e.g.
"If you are using an older version of CMake, such as the one with Ubuntu versions older than 23.04" (23.04 has v3.25.1; can't find the version with 22.10 since it is no longer supported).

**Comment by vavanade** [comment]
I managed to solve it by installing the newest version of CMake by running the official script at `https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-linux-x86_64.sh`.
