### ISSUE TITLE
Training with multiple GPUs is not faster than 1 GPU???

### ISSUE THREAD

**Issue by aidevmin** [hank-ai/darknet#5]
I follow the guide to train my dataset with multiple GPUs, I saw speed of 2 cases is same. I use the same config 
```
batch=64
subdivisions=32     # 16 OOM
width=512
height=512
```
I check GPU usage and almost GPU is used. Does Darknet support multiple GPUs?

**Comment by stephanecharette** [comment]
> Does Darknet support multiple GPUs?

Yes.  See the readme for details.  https://github.com/hank-ai/darknet/blob/master/README_previous.md#how-to-train-with-multi-gpu

**Comment by aidevmin** [comment]
@stephanecharette 
My issue is that speed of multiple GPU training is not faster than speed of 1 GPU training. It is not solved. 

Please open it again.
