### ISSUE TITLE
Yolov9

### ISSUE THREAD

**Issue by SheldonWBM** [hank-ai/darknet#50]
YOLOv9 was published roughly a week ago, in Feb 2024: https://github.com/AlexeyAB/darknet/issues/8887 
Feature request: Darknet framework compatible with YOLOv9.

**Comment by 1027663760** [comment]
Compared to other frameworks, Darknet does not have too many dependencies and is easy to integrate. I hope to see major updates to Darknet in the future

**Comment by stephanecharette** [comment]
See the discussions surrounding YOLOv9 in the Darknet/YOLO discord server channels.

**Comment by stephanecharette** [comment]
Darknet/YOLO is still faster and performs better than the commercial YOLOv7, YOLOv8, YOLOv9, and YOLOv10:  https://www.youtube.com/watch?v=2Mq23LFv1aM

Closing.
