### ISSUE TITLE
error: building tiff:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by raduhawk** [hank-ai/darknet#52]
Hi! I`m trying to follow the steps for building darknet on windows 11 but i`m facing this error when i try to install opencv:

C:\src\vcpkg>.\vcpkg.exe install opencv[contrib,dnn,freetype,jpeg,openmp,png,webp,world]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * leptonica:x64-windows@1.84.1
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows@3.7.2
  * libiconv:x64-windows@1.17#3
  * libxml2[core,iconv,lzma,zlib]:x64-windows@2.11.7
  * lz4:x64-windows@1.9.4#1
    opencv[contrib,core,default-features,dnn,freetype,jpeg,openmp,png,webp,world]:x64-windows@4.8.0#1
  * opencv4[contrib,core,default-features,dnn,freetype,jpeg,openmp,png,quirc,tiff,webp,world]:x64-windows@4.8.0#15
  * openssl:x64-windows@3.2.1#2
  * protobuf:x64-windows@3.21.12#1
  * quirc:x64-windows@1.2
  * tesseract:x64-windows@5.3.4
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * vcpkg-get-python-packages:x64-windows@2024-01-24
  * zstd:x64-windows@1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 3 package(s) from C:\Users\Radu\AppData\Local\vcpkg\archives in 973 ms. Use --debug to see more details.
Installing 1/15 tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4...
Building tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4...
-- Using cached libtiff-libtiff-v4.6.0.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/tiff/src/v4.6.0-cea7694842.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/libtiff-libtiff-v4.6.0.tar.gz
-- Applying patch FindCMath.patch
-- Applying patch requires-lerc.patch
-- Using source at C:/src/vcpkg/buildtrees/tiff/src/v4.6.0-cea7694842.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/src/vcpkg/buildtrees/tiff/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\tiff\config-x64-windows-dbg-CMakeCache.txt.log
      C:\src\vcpkg\buildtrees\tiff\config-x64-windows-rel-CMakeCache.txt.log
      C:\src\vcpkg\buildtrees\tiff\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/tiff/portfile.cmake:33 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

error: building tiff:x64-windows failed with: BUILD_FAILED
Elapsed time to handle tiff:x64-windows: 7.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tiff]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by stephanecharette** [comment]
Note this is a vcpkg error, not a darknet error.  You also should look at the log files:

    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/src/vcpkg/buildtrees/tiff/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
    C:\src\vcpkg\buildtrees\tiff\config-x64-windows-dbg-CMakeCache.txt.log
    C:\src\vcpkg\buildtrees\tiff\config-x64-windows-rel-CMakeCache.txt.log
    C:\src\vcpkg\buildtrees\tiff\config-x64-windows-out.log
