### ISSUE TITLE
Difference between this repo and Alexyab

### ISSUE THREAD

**Issue by EvanBrownVTM** [hank-ai/darknet#6]
What updates have been made to this repo from Alexyab original? 
Also, is yolov7 currently working?

**Comment by stephanecharette** [comment]
You can find the list of commits here:  https://github.com/hank-ai/darknet/commits/stephane-dev
and here:  https://github.com/hank-ai/darknet/commits/master

And yes, YOLO7 is working, no changes have been made to it.
