### ISSUE TITLE
darknet.py references load_image_color, which was removed

### ISSUE THREAD

**Issue by jake-nz** [hank-ai/darknet#65]
`load_image_color` was removed here: https://github.com/hank-ai/darknet/commit/d3e3339bbb9669a6b2fd243d84df8beb362dce4f#diff-1669d998bbe197992292514f3da1f46a151d50cd474e33d5407a307897942fa0

It's still referenced here: https://github.com/hank-ai/darknet/blob/6bcf92b17fa4d6dfd8908a7f45c00a1ad9af970b/src-python/darknet.py#L429

Which causes python code to fail with: `AttributeError: /usr/lib/libdarknet.so: undefined symbol: load_image_color`

This change seems to work for me, but I'm not familiar enough with this project to know if other changes are needed to:

```py
load_image = lib.load_image
load_image.argtypes = [c_char_p, c_int, c_int, c_int]
```

**Comment by stephanecharette** [comment]
Thank you.  Fixed in v2.0.211.
