### ISSUE TITLE
Windows Vs Linux Performance Difference

### ISSUE THREAD

**Issue by Statgator2** [hank-ai/darknet#68]
Has anyone else ever taken the exact same dataset with the same bounding boxes and trained on Linux and run in Linux vs trained in Windows and running in Windows?

If so, did you witness a performance difference?

I'm getting thousands of boxes in Windows when I lower the confidence but that is not happening in Linux.  In Linux I'm getting logical detections but in Windows the detentions are mostly illogical.

Curious if anyone else has witnessed this.

Thanks

**Comment by stephanecharette** [comment]
This is a repeat of the same question you had on the old AlexeyAB repo.  :(  As I wrote to you there, I do this often, both Windows and Linux.  It works on both, as well as on ARM devices as well.

I also have some sample datasets available [from the FAQ](https://www.ccoderun.ca/programming/yolo_faq/#datasets) where people have used to train on both Windows and Linux.  These are often discussed on the discord channel.  No-one has reported the problems you talk about here.

Run `darknet --version` to show us the version you're running, and also post the exact command you are using to train.

**Comment by jklemmack** [comment]
Can you provide more details or at least an example of your configuration and data files, and example outputs?  You are broadly saying "it doesn't work (for me)" and leaving a massive amount of work to someone else to either try and prove that it does, or guess at what your issue might be.

**Comment by stephanecharette** [comment]
No new comment in 4 months.  Closing.

If you have more information, please re-open with the necessary details.
