### ISSUE TITLE
"c:/src/" directory 

### ISSUE THREAD

**Issue by jnie0808** [hank-ai/darknet#75]
Hi,
Is  "c:/src/" directory still useful after installation?
Thanks

**Comment by stephanecharette** [comment]
If you've installed the darknet file and it copied everything into `C:\Program Files\Darknet\...` then you can safely delete the entire `C:\src\` tree.

But you may want to hang on to it for when there are updates available.  Will be easier to rebuild new versions without having to start from scratch.

**Comment by jnie0808** [comment]
Thank you, Stephane. Everything is compiled and copied to the destination. 
Just a little bit of missing the 20G space on drive C:.

**Comment by jnie0808** [comment]
DIY close :)
