### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by richardp4** [hank-ai/darknet#76]
Hi, 
when i build the darknet, I encounter the problem.
My gpu is nvidia 4060ti  and OS is ubuntu 20.04.
Please let me know how to fix this problem.

$ make -j4 package
nvcc fatal   : Unsupported gpu architecture 'compute_89'
make[2]:  [src-lib/CMakeFiles/darknetobjlib.dir/build.make:108: src-lib/CMakeFiles/darknetobjlib.dir/activation_kernels.cu.o] Error 1
make[2]:  Waiting for unfinished jobs....
/home/mc/src/darknet/src-lib/activations.cpp: In function ‘float gradient(float, ACTIVATION)’:
/home/mc/src/darknet/src-lib/activations.cpp:362:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
  362 |    darknet_fatal_error(DARKNET_LOC, "should be used custom NORM_CHAN or NORM_CHAN_SOFTMAX-function for gradient");
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/mc/src/darknet/src-lib/activations.cpp:363:3: note: here
  363 |   case ELU:

**Comment by stephanecharette** [comment]
> nvcc fatal : Unsupported gpu architecture 'compute_89'

This is because you are attempting to compile for a RTX 4060, but you are using an older version of CUDA that does not support the 40xx architecture.

Solution:  make sure you are using the right drivers and software for your hardware.

**Comment by Hab2Verer** [comment]
Hello @stephanecharette 
Love your work!

I am running into the same problem 
I have an NVIDIA GeForce RTX 4050 on Ubuntu 22.04 (laptop)

`nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
`
`nvidia-smi    
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   36C    P8              2W /   80W |      64MiB /   6141MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
`

Any idea what might be causing this problem?

**Comment by Hab2Verer** [comment]
Nevermind 
I had to start the building procedure from scratch

Solved!
