### ISSUE TITLE
wrong order of strides in cudnn maxpool descriptor

### ISSUE THREAD

**Issue by swdn133** [hank-ai/darknet#77]
File: 
src-lib/maxpool_layer.cpp

Issue: 
When creating cudnnSetPooling2dDescriptor, the parameters stride_y and stride_x are set. According to the cudnn documentation of cudnnSetPooling2dDescriptor, the order of vertical (y) and horizontal(x) strides is wrong. (see here: https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-897/api/index.html#cudnnSetPooling2dDescriptor)

Fix:
As easy as switching the parameters. I already implemented it here: https://github.com/swdn133/darknet/commit/fceb9200d38957b65dfa7c8ecae88963173f2731

If you agree, I would just create a merge request with the fix as mentioned above.

**Comment by stephanecharette** [comment]
Oh, interesting!  Yes, it does appear to be backwards.  I wonder what the implications will be.

Yes, please do a pull request on the `v3-dev` branch and I'll merge it in.

**Comment by stephanecharette** [comment]
I did a few tests where I printed out both stride_x and stride_y just to see what kind of values are used.  In my tests, both values were set the same value of `2`, so no difference.

I'd have to dig into the code to see where these `stride_` values comes from to see where/how they might be different.  But definitely, send me a PR and your name will be on the change.

**Comment by swdn133** [comment]
It comes from the config. If you just use the parameter `stride` in your [maxpool] config, it broadcasts the same value for stride_x and stride_y. But you also have the option to specify `stride_x` and `stride_y` values directly if you want to do some non-quadratic pooling. 
You can find this behaviour in line 905ff. in `src-lib/parser.cpp`

**Comment by stephanecharette** [comment]
Pull request #78 was merged into V3 a while back.  Closing.
