### ISSUE TITLE
PATH too long installer unable to modify PATH!

### ISSUE THREAD

**Issue by Sci3nce** [hank-ai/darknet#81]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/6104d184-5742-431a-81df-8a2db2cf6a34">

Windows 10, 64-bit, build 19045
Darknet v2.0-226-g39868921
CUDA runtime version 12060 (v12.6), driver version 12060 (v12.6)
cuDNN version 12060 (v9.4.0), use of half-size floats is ENABLED
=> 0: NVIDIA GeForce RTX 4090 [#8.9], 24.0 GiB
OpenCV v4.8.0

I enabled the long registry path in the Windows registry. I also shortened my PATH considerably, putting all of the Visual Studio entries into their own separate variable. My current character count for my PATH is 917. 

I'm following these instructions: 
https://github.com/hank-ai/darknet

**Comment by stephanecharette** [comment]
Not a Darknet problem, but a Windows & NSIS limitation.

https://www.google.com/search?q=nsis+path+too+long+installer+unable+to+modify+path
