### ISSUE TITLE
while trying to run training on custom dataset [Rolodex] for detection, it is failing with signal 6 abort , please help me resolve this.

### ISSUE THREAD

**Issue by amit321kumar** [hank-ai/darknet#84]
To report a bug, please provide the following:

* the output of the `darknet version` command

Darknet v2.0-226-g39868921
CUDA runtime version 12020 (v12.2), driver version 12020 (v12.2)
cuDNN version 12020 (v8.9.6), use of half-size floats is ENABLED
=> 0: Tesla T4 [#7.5], 14.7 GiB
OpenCV v4.5.4

* the exact command you ran

!darknet detector train  Rolodex.data rolo.cfg yolov4-tiny.weights Rolodex.names

* the operating system you are using

Google colab/kaggle notebook with GPU enabled Linux

If relevant, please attach a screenshot showing the problem.
please find the below screen shot of same error .

![darknet_error](https://github.com/user-attachments/assets/76f0d0ea-66f3-4ff9-9591-f62fbf854a1a)

**Comment by stephanecharette** [comment]
Note the command you ran is invalid.  The proper training command is documented in the FAQ and in the README.  See:  https://www.ccoderun.ca/programming/yolo_faq/#training_command

**Comment by amit321kumar** [comment]
Thanks for your quick response @stephanecharette , it was because -dont_show argument missing in train command .
Thanks again !! 😄

**Comment by stephanecharette** [comment]
> Thanks for your quick response @stephanecharette , it was because -dont_show argument missing in train command . Thanks again !! 😄

No, that is not the problem.  Please see the training command as documented in the readme or in the FAQ.

**Comment by amit321kumar** [comment]
![Uploading IMG_20241021_084939.jpg…]()

**Comment by amit321kumar** [comment]
![IMG_20241021_084939](https://github.com/user-attachments/assets/a746933d-7421-4aab-8445-def1d9a6aaff)

**Comment by stephanecharette** [comment]
I already told you -- twice! -- that you are running an invalid command.  I cannot help you if you refuse to read.

Please read the FAQ and/or read the README which tells you the command you should be running.

**Comment by amit321kumar** [comment]
Thanks again @stephanecharette  ,training is successful ..second issue was because of corrupt dataset .Request you to add a feature to export  it to onnx format .💐
