### ISSUE TITLE
v3 windows build error

### ISSUE THREAD

**Issue by jkelin** [hank-ai/darknet#85]
Hi, I'm trying to build Darknet with CUDA support on Windows but I'm getting an error. I have a clean windows VM, have followed the steps in the readme including installing CUDA after Visual Studio. Building branch `v2` [works fine](https://pastebin.com/rZN5zeFz).

The VM doesn't have a GPU attached and I see some warnings about that, but hopefully that shouldn't be critical. I've also tried on normal windows machine with GPU and got the same error.

Running `msbuild.exe /property:Platform=x64;Configuration=Release /target:Build -maxCpuCount -verbosity:normal -detailedSummary darknet.sln`

Results in (see [full log](https://pastebin.com/qRDyVyB6)):
```
       "C:\Projects\darknet\build\darknet.sln" (Build target) (1) ->
       "C:\Projects\darknet\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "C:\Projects\darknet\build\src-lib\darknet.vcxproj.metaproj" (default target) (3) ->
       "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj.metaproj" (default target) (4) ->
       "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj" (default target) (18) ->
       "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj" (CudaBuildCore target) (18:6) ->
       (CudaBuildCore target) ->
         C:\Projects\darknet\src-lib\convolutional_kernels.cu(613): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
         C:\Projects\darknet\src-lib\convolutional_kernels.cu(951): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
         C:\Projects\darknet\src-lib\convolutional_kernels.cu(961): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
         C:\Projects\darknet\src-lib\convolutional_kernels.cu(967): error : identifier "col2im_gpu_ext" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxp
       roj]
         C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.6.targets(799,9): error MSB3721: The command ""C:\P
       rogram Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\1
       4.41.34120\bin\HostX64\x64" -x cu   -I"C:\Projects\darknet\src-cli" -I"C:\Projects\darknet\src-lib" -I"C:\Projects\darknet\src-other" -I"C:\Projects\darknet\src-li
       b\windows" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -I"C:\Projects\vcpkg\installed\x64-windows\include" -I"C:\Program Files\NVIDIA GPU
       Computing Toolkit\CUDA\v12.6\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart static -std=c++17 -arch=native -Xcompiler="/EHsc
        -Ob2"   -D_WINDOWS -DNDEBUG -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Release\"" -D_MBCS
        -DWIN32 -D_WINDOWS -DNDEBUG -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Release\"" -Xcompi
       ler "/EHsc /W1 /nologo /O2 /FS   /MD " -Xcompiler "/Fddarknetobjlib.dir\Release\darknetobjlib.pdb" -o darknetobjlib.dir\Release\convolutional_kernels.obj "C:\Proje
       cts\darknet\src-lib\convolutional_kernels.cu"" exited with code 2. [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]

    124 Warning(s)
    5 Error(s)
```

**Comment by stephanecharette** [comment]
Building with CUDA without a supported GPU is not supported.  As far as I know, this was never supported in v2 either.

Nothing should have changed between v2 and v3 when it comes to CUDA.  Not sure how you are trying to force building with CUDA on hardware that does not support it.  When I try to build on Windows, CMAKE correctly detects that CUDA is not available, like this:

![image](https://github.com/user-attachments/assets/120ba702-d14d-430b-88ea-fadeee294655)

If I follow the usual build steps for building on Windows, V3 does build correctly:

![image](https://github.com/user-attachments/assets/e7cc6291-16e4-426f-9fe3-c9e80eba98b6)

Let me know what you've modified to try and force CUDA without a GPU, and if you have any ideas on what needs to be done to fix it.

**Comment by jkelin** [comment]
> Building with CUDA without a supported GPU is not supported. As far as I know, this was never supported in v2 either.

Oh I see. My V2 build works, but I'd love to try out the sweet performance improvements promised by V3. Honestly I'm not sure what I've changed in my Windows environment with GPU, I've had the same system for years, I'm sure I've had previous CUDA versions installed as well as other libraries that may have interfered. I'll try to get a build running in separate partition with clean install sometime.

I wonder, is there a reason why you don't/can't publish binary builds for individual Dark projects? You already have working (for most people) pipeline to create .deb and windows installers - why not jut plop them into GitHub releases rather than field support for people with build issues like me? 🙂

**Comment by stephanecharette** [comment]
What GPU should I build for?  What CUDA driver version should I use?  What CPU should I optimize for?  Darknet is very dependent on and optimized for the hardware on which it will run.

Even for a single GPU, let's say we pick RTX 2080 for example.  Should I build using CUDA 11.2?  12.0?  12.1?  And there are dozens of CPU types.  So for any given hardware, we'd have dozens of builds.  Then multiply that by every GPU.  We'd have several hundreds builds for every commit.

**Comment by Nastyga** [comment]
![179425274-f55a36d4-8450-4471-816b-8c105841effd](https://github.com/user-attachments/assets/e20a0159-a419-4649-bbc5-8f7728701c4f)

**Comment by jkelin** [comment]
Sorry for not answering. In the end I couldn't manage to get a complete build going. CUDA was OK, but cuDNN just didn't work, even on a clean computer with a GPU. I've ended up training with Ultralytics YOLO and doing inference with DirectML and ONNX.

**Comment by stephanecharette** [comment]
But you did get it to compile after the fix I made?  You just couldn't get it to recognize or find cuDNN?

You should have joined the discord server.  Lots of users there could have helped out.

**Comment by stephanecharette** [comment]
(The "fix" I referenced in the last comment is issue #86.)
