### ISSUE TITLE
I need a Good site bank hacking

### ISSUE THREAD

**Issue by Nastyga** [hank-ai/darknet#89]
Please describe the feature as de

tailed as possible.
Provide links to the paper or source code if it exist.

- [ ] `
![1728868471539](https://github.com/user-attachments/assets/51984173-08de-4e35-aba5-90c7a72177f7)
`

**Comment by stephanecharette** [comment]
Closing.  Get familiar with the project before you post an issue.

**Comment by Nastyga** [comment]
"C:Projects\darknet\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
>        "C:\Projects\darknet\build\src-lib\darknet.vcxproj.metaproj" (default target) (3) ->
>        "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj.metaproj" (default target) (4) ->
>        "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj" (default target) (18) ->
>        "C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj" (CudaBuildCore target) (18:6) ->
>        (CudaBuildCore target) ->
>          C:\Projects\darknet\src-lib\convolutional_kernels.cu(613): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
>          C:\Projects\darknet\src-lib\convolutional_kernels.cu(951): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
>          C:\Projects\darknet\src-lib\convolutional_kernels.cu(961): error : identifier "gemm_ongpu" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxproj]
>          C:\Projects\darknet\src-lib\convolutional_kernels.cu(967): error : identifier "col2im_gpu_ext" is undefined [C:\Projects\darknet\build\src-lib\darknetobjlib.vcxp
>        roj]
>          C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 12.6.targets(799,9): error MSB3721: The command ""C:\P
>        rogram Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\1
>        4.41.34120\bin\HostX64\x64" -x cu   -I"C:\Projects\darknet\src-cli" -I"C:\Projects\darknet\src-lib" -I"C:\Projects\darknet\src-other" -I"C:\Projects\darknet\src-li
>        b\windows" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -I"C:\Projects\vcpkg\installed\x64-windows\include" -I"C:\Program Files\NVIDIA GPU
>        Computing Toolkit\CUDA\v12.6\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart static -std=c++17 -arch=native -Xcompiler="/EHsc
>         -Ob2"   -D_WINDOWS -DNDEBUG -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Release\"" -D_MBCS
>         -DWIN32 -D_WINDOWS -DNDEBUG -DGPU -DH5_BUILT_AS_DYNAMIC_LIB -DOPENMP -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D"CMAKE_INTDIR=\"Release\"" -Xcompi
>        ler "/EHsc /W1 /nologo /O2 /FS   /MD " -Xcompiler "/Fddarknetobjlib.dir\Release\darknetobjlib.pdb" -o

**Comment by Nastyga** [comment]
https://www.facebook.com/profile.php?id=100077536848813

**Comment by stephanecharette** [comment]
What are you doing posting facebook links?  This is not the dark web, this is Darknet/YOLO.

Do a google search if you're not familiar with Darknet/YOLO.

As for the error you pasted above, exactly which version are you trying to build?  Run "git describe" in the Darknet/YOLO source directory and paste the output.

**Comment by jkelin** [comment]
It's a bot, that snippet is copied from my previous issue. Best report it
