### ISSUE TITLE
What is not working on Darknet for ARM?

### ISSUE THREAD

**Issue by vsaw** [hank-ai/darknet#9]
I noticed the following item on the roadmap "fix ARM build (Jetson devices)" and was wondering what exactly is not working on ARM devices.

(I've been trying to get Darknet working on Jetpack 5 for the last 48h and was wondering if you know why it's not working. You can read up on my progress here https://github.com/opendatacam/opendatacam/issues/607)

**Comment by stephanecharette** [comment]
I've made a lot of modifications recently to the build process.  As you've noted, I do have a task on the roadmap to verify everything on the Jetson devices, but I've not gotten around to that yet.

**Comment by vsaw** [comment]
I see, I thought there was known issues for the platforms. Thanks for the quick answer 🙏
