### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by Bpable** [hank-ai/darknet#93]
I've ran my model on both this version of darknet, and the latest AlexeyAB darknet. Both have returned false positives when testing. I've also tested it on other cfgs & weights files including the default yolov3 & yolov4 files. Do you have any insights to offer for what may be causing this.

Below is a case of the yolov4 weight & cfg with coco.names.
![00010672](https://github.com/user-attachments/assets/f2fc351f-6f40-4dcf-9ba3-8118ab1823cb)

This is a custom weight, cfg, and name.
![00010002](https://github.com/user-attachments/assets/3cdc244e-fd22-4cd4-a4c0-787767bb50f3)

**Comment by stephanecharette** [comment]
1) The github issues are meant to report bugs in the software, not for general support.  Please join the Discord server if you want to chat about your results.  https://discord.gg/zSq8rtW

2) You didn't provide the command you are running, how you trained, how you verified your dataset, etc.  Including 2 images is a good way for us to visualize the problem you are experiencing, but does not give us enough information to replicate the problem.

3) You say "yolov4 weight & cfg with coco.names" ... but you're not really using the MSCOCO weights are you?  Note this text in the readme:

> The MSCOCO pre-trained weights are provided for demo-purpose only.

And:

> Note that people are expected to train their own networks. MSCOCO is normally used to confirm that everything is working correctly.

Source:  https://github.com/hank-ai/darknet#mscoco-pre-trained-weights

4) Have you consulted the FAQ?  There is a section called "If the results aren't great" which lists a few things to check.  See here:  https://www.ccoderun.ca/programming/yolo_faq/  There are 7 bullets points in that section.  Can you let us know which ones apply to you, and what the answers are when it comes to your network?

But again, what you really should be doing is asking on the Darknet/YOLO discord server if you want to chat about the results.
