### ISSUE TITLE
DarkMark - Heatmaps on Images

### ISSUE THREAD

**Issue by jredmondson** [hank-ai/darknet#95]
### Summary

Recently, a feature was added to Darknet that allows for generating heatmaps from the yolo layers in models. From my understanding, this may be useful for answering questions like "what parts of the image are resulting in the projected classification". From talking with team members on one of our projects, this could be a very helpful addition to DarkMark in allowing for a model to be trained and then have data engineers step through images in the training or test set (i.e., images not used in training the model) to understand how the model's filters/layers are responding during image classification.

### Goal/Deliverable

* Configurable option (e.g., when right clicking in DarkMark) to enable heatmap overviews on images

### Links

* [Heatmap code](https://github.com/hank-ai/darknet/blob/b4b25d339a084b8ada4764846f4d532b9873fee0/src-lib/yolo_layer.cpp#L1607)

**Comment by stephanecharette** [comment]
This should have been opened as a DarkMark issue, not Darknet.

Support for heatmaps has been added to DarkMark:  https://github.com/stephanecharette/DarkMark/commit/e442f55bb4319d40e8c94492580a8ea6292da8cd

**Comment by stephanecharette** [comment]
Video showing how to use it has been uploaded:  https://youtu.be/XocrbSTSW1Q

Closing new feature issue.
