### ISSUE TITLE
DarkMark - Organization/Sorting Features

### ISSUE THREAD

**Issue by jredmondson** [hank-ai/darknet#96]
### Summary

When dealing with really large datasets (e.g., 50k-500k images), sorting and filtering options can be really helpful to prune and shape a dataset and respond to issues encountered in a trained model. For instance, if there are 50k-500k negative images, but many of the negative images were first introduced to a dataset before a specific caption was added to the names file, then many of these negative images may need to be marked up for proper captioning.

There's an opportunity to save users a significant amount of time in DarkMark by providing some sorting and filtering options that might be accessible from the right-click context menu in a manner similar to `review iou`. It would be nice to have a column for projected classification confidence for images that is populated when the analysis is selected (e.g., by clicking a `review captions`) that would allow for sorting and filtering by:

1. The "marked" caption by the user / data preparer. This way, users can focus on a caption and isolate what they're looking at based on what they originally marked.  This should be any caption in the dataset as defined in the .names file, but also should include an option for `negative image` or similar as the benefits of this may be especially useful for negative images and miscaptioning
2. The projected caption by the weights file, if it's included and training has already occurred.
3. The projected caption confidence. If this can be sorted by, it would be really helpful, because when analyzing a large dataset, high confidence misclassifications have priority because when running predict, you can set a minimum threshold to weed out many false positives where scenes/environments are ambiguous. A sort would allow users to look at the highest confidence misclassifications and potentially analyze them and/or fix them
4. The directory of the image. If we can filter by this, it can help with isolating where problems are occurring. By simply listing this field and potentially sorting it, users have more control over their organization and analysis focus
5. The image name. This just included for completeness of what I believe the feature needs to be informative.

When a user clicks on a row, it should bring up the image, similar to how other `review` features work in DarkMark currently.

### Goal/Deliverable

1. Right click context menu for analyzing, sorting, and filtering projected captions on images
2. Window for sorting/filtering columns for marked caption, projected captions, confidence, etc.
3. Click through functionality for bringing up images to better understand why projected captions may not reflect marked captions

**Comment by jredmondson** [comment]
Hi @stephanecharette . Any updates on this sorting by projected caption confidence feature?

**Comment by stephanecharette** [comment]
Sorry, I just finished the heatmap changes around 5am this morning.  I haven't started on this yet.

**Comment by stephanecharette** [comment]
Commit just pushed for DarkMark which introduces several new sort functions.  Hoping this will address some of the issues in this ticket.  Will make a video soon showing how this works.  https://github.com/stephanecharette/DarkMark/commit/a8d4081f154d803fad819c6f7fcc4c032c3a60f9

Note this is actually part of DarkMark, not Darknet.  Issue was originally created in the wrong repo.  See:  https://github.com/stephanecharette/DarkMark

**Comment by stephanecharette** [comment]
Video showing how these new sort options work:  https://youtu.be/7SH5FDU9uZc

**Comment by jredmondson** [comment]
From feedback I've received, I believe this is close-able unless you have some other features you were wanting to include
