### ISSUE TITLE
Build Darknet on Jetson Orin Nano with GPU Support

### ISSUE THREAD

**Issue by sminkwitz** [hank-ai/darknet#98]
Hey, when i follow the instructions of building darknet and run the command darknet version i got the following : Darknet V3 "Jazz" v3.0-204-ga87ab7d5-dirty
Darknet is compiled to only use the CPU.  GPU is disabled.
OpenCV v4.5.4, Ubuntu 20.04

How to build darknet with GPU support for jetson orin nano. 

i have CUDA: 11.4.315, cuDNN 8.6.0.166 installed

**Comment by sminkwitz** [comment]
okay i got it working by this source https://qengineering.eu/install-darknet-on-orin-nano.html ... but what is the difference between hank-ai and the AlexeyAB/darknet repo...?

**Comment by stephanecharette** [comment]
> but what is the difference between hank-ai and the AlexeyAB/darknet repo...?

https://www.ccoderun.ca/programming/yolo_faq/#what_software_is_used
